version: '3'
services:
  db:
    build: ./docker/
    ports:
      - "5433:5432"
    container_name: postgres
  core-module:
    build: ./app-core/
    ports:
      - "8081:8080"
    container_name: core-module
    links:
      - db:host-banco
  web-module:
    build: ./app-web/
    ports: 
      - "8080:8080"
    container_name: web-module
    links:
      - core-module:host-core
